name: Lint code

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: pnpm install
    - name: Build additional files
      run: pnpm build
    - name: Run ESLint
      run: pnpm lint