name: Deploy API

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# todo: use this instead of npm run dev: (in the pm2 program)
# npm run build
# npm run start -> cause an issue, needs to be fixed first

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH }}
        script: |
          cd /var/www/html/api.compliancepack.net/
          git stash
          git pull
          npm install --save
          pm2 restart "API"